In [10]:
import numpy as np

In [42]:
class Knap_sack:
    def __init__(self,weights,values,capacity):
        self.weights = weights
        self.values = values
        self.capacity = capacity
        self.no_of_items = len(self.weights)

    def dynamic_programming(self):
        dp = np.zeros((self.no_of_items + 1, self.capacity + 1), dtype = int)

        for i in range(1, self.no_of_items + 1):
            for w in range(1, self.capacity + 1):

                if self.weights[i - 1] > w:
                    dp[i][w] = dp[i - 1][w]

                else:
                    dp[i][w] = max(dp[i -1][w],dp[i - 1][w - self.weights[i -1]] + self.values[i - 1])
            print(dp)
        max_value = dp[self.no_of_items][self.capacity]
        print(max_value)

        selected_items1 = []

        w, i = self.capacity,self.no_of_items
        while i > 0 and w > 0:
            if dp[i][w] != dp[i - 1][w]:
                selected_items1.append(i - 1)
                w -= self.weights[i - 1]
            i -= 1
        print(f'Selected items:{selected_items1}')


if __name__ == '__main__':
    weights = np.array([3,4,6,5])
    values = np.array([2,3,1,4])
    capacity = 8
    k = Knap_sack(weights,values,capacity)
    k.dynamic_programming()

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 2 2 2 2 2 2]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 2 2 2 2 2 2]
 [0 0 0 2 3 3 3 5 5]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 2 2 2 2 2 2]
 [0 0 0 2 3 3 3 5 5]
 [0 0 0 2 3 3 3 5 5]
 [0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 2 2 2 2 2 2]
 [0 0 0 2 3 3 3 5 5]
 [0 0 0 2 3 3 3 5 5]
 [0 0 0 2 3 4 4 5 6]]
6
Selected items:[3, 0]
